"""
SecureTrack Platform Ã¢â‚¬â€ User Model
Centralized identity for Admins, Supervisors, Guards, Outdoor personnel, and Clients.
"""
from sqlalchemy import Column, String, Float, DateTime, Boolean, Numeric, Index
from sqlalchemy.orm import relationship
from datetime import datetime, timezone

from app.enums import UserStatus
from app.core.database import Base


class User(Base):
    __tablename__ = "users"
    __table_args__ = (
        Index('ix_users_role_active', 'role', 'is_active'),
    )

    user_id = Column(String(36), primary_key=True, index=True)
    name = Column(String(255), nullable=False)
    email = Column(String(255), nullable=False, unique=True, index=True)
    phone_number = Column(String(20), nullable=True)
    password_hash = Column(String(255), nullable=False)
    role = Column(String(30), nullable=False, default="guard")

    # Badge / employee number (unique within company)
    badge_number = Column(String(50), nullable=True, unique=True, index=True)

    # Employee code Ã¢â‚¬â€ generated by Nasr City recruitment office
    employee_code = Column(String(50), nullable=True, unique=True, index=True)

    # Region assignment (for regional managers and filtered queries)
    region = Column(String(100), nullable=True, index=True)

    # Real-time GPS (updated by mobile app)
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)

    # Profile
    profile_image_url = Column(String(500), nullable=True)
    is_active = Column(Boolean, nullable=False, default=False)  # Pending admin approval by default
    fcm_token = Column(String(500), nullable=True)  # Firebase Cloud Messaging token for push notifications
    status = Column(String(30), nullable=False, default=UserStatus.PENDING)  # pending status
    requested_role = Column(String(30), nullable=True)  # role requested during registration

    # Payroll
    base_salary = Column(Float, nullable=True, default=0.0)  # Monthly base salary in EGP
    daily_rate = Column(Float, nullable=True, default=0.0)  # Daily rate (derived from classification)
    classification = Column(String(50), nullable=True)
    shift_type = Column(String(10), nullable=True)  # ص (morning) / م (evening)  # Ã™â€ Ã˜Â§Ã˜Â¦Ã˜Â¨/Ã™â€¦Ã˜Â´Ã˜Â±Ã™Â/Ã™ÂÃ˜Â±Ã˜Â¯ Ã¢â‚¬â€ drives salary tier

    # HR fields
    hire_date = Column(DateTime, nullable=True)
    insurance_status = Column(String(30), nullable=True, default='none')  # Ã™â€¦Ã˜Â¤Ã™â€¦Ã™â€ /Ã˜Â®Ã˜Â§Ã˜Âµ/Ã˜Â¨Ã˜Â¯Ã™Ë†Ã™â€ 
    bank_account = Column(String(100), nullable=True)
    transfer_name = Column(String(255), nullable=True)       # ?????? ??
    transfer_method = Column(String(100), nullable=True)     # ????? ???????
    payroll_amount = Column(Float, nullable=True, default=0.0)  # Fixed PAYROLL value (BY column)

    # Timestamps
    created_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc))
    updated_at = Column(DateTime, nullable=False, default=lambda: datetime.now(timezone.utc),
                        onupdate=lambda: datetime.now(timezone.utc))

    # Relationships
    supervisor_routes = relationship("SupervisorRoute", back_populates="supervisor", foreign_keys="SupervisorRoute.supervisor_id")
    supervisor_visits = relationship("SupervisorVisit", back_populates="supervisor", foreign_keys="SupervisorVisit.supervisor_id")
    guard_rosters = relationship("GuardRoster", back_populates="guard", foreign_keys="GuardRoster.guard_id")
    devices = relationship("DeviceRegistry", back_populates="user", foreign_keys="DeviceRegistry.user_id")
    notifications = relationship("Notification", back_populates="user", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<User(user_id={self.user_id}, name={self.name}, role={self.role})>"

